version: '2'
services:
  #可以使用服务名来连接其他容器
  discovery:
    image: macro/eureka-server:0.0.1-SNAPSHOT
    ports:
    - "1111:1111"
  hello-service:
    image: macro/hello-service:0.0.1-SNAPSHOT
    ports:
      - "8080:8080"
  feign-consumer:
    image: macro/feign-consumer:0.0.1-SNAPSHOT
    ports:
      - "9001:9001"
  api-gateway:
    image: macro/api-gateway:0.0.1-SNAPSHOT
    ports:
      - "5555:5555"
