version: '2'
services:
  peer1:
    image: macro/eureka-server:0.0.1-SNAPSHOT
    ports:
    - "1111:1111"
    environment:
       - spring.profiles.active=peer1
  peer2:
    image: macro/eureka-server:0.0.1-SNAPSHOT
    ports:
      - "1112:1112"
    environment:
      - spring.profiles.active=peer2
